language: go

sudo: false

os:
    - linux
    - osx

go:
    - 1.8.x
    - 1.9.x
    - 1.10.x
    - tip

branches:
    only:
        - master
        - /^v\d+\.\d+\.\d+(-\S*)?$/

matrix:
    fast_finish: true
    allow_failures:
        - go: tip

before_install: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

install: dep ensure -vendor-only

script: go test

deploy:
    provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
        tags: true
        condition: $TRAVIS_OS_NAME = linux && $TRAVIS_GO_VERSION =~ ^1\.10(\.[0-9]+)?$
